name: Lint

on:
  pull_request:
    branches: 
      - main

jobs:
  lint:
    name: Run Biome
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run linting and formatting checks
        run: pnpm lint 
        
